ekf_filter_node:
  ros__parameters:
    # 1. TẦN SỐ TÍNH TOÁN
    frequency: 20.0 # Khớp với 20Hz của STM32
    sensor_timeout: 0.2 # Đợi sensor tối đa 200ms
    two_d_mode: true # Robot chạy trên mặt phẳng

    # 2. KHUNG TỌA ĐỘ
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom # EKF chỉ lo nhánh odom -> base_link

    publish_tf: true # BẮT BUỘC để RViz thấy robot

    # 3. CẤU HÌNH ENCODER (Topic /odom từ file Python)
    odom0: odom
    odom0_config: [
        false,
        false,
        false, # x, y, z
        false,
        false,
        false, # roll, pitch, yaw
        true,
        false,
        false, # vx (Lấy vận tốc tịnh tiến từ bánh xe)
        false,
        false,
        false, # vy, vz, roll velocity
        false,
        false,
        false, # pitch velocity, yaw velocity
        false,
        false,
        false,
      ] # acceleration
    odom0_differential: false

    # 4. CẤU HÌNH IMU (Topic /imu/data từ file Python)
    imu0: imu/data
    imu0_config: [
        false,
        false,
        false, # x, y, z
        false,
        false,
        true, # roll, pitch, YAW (Góc hướng từ BNO055)
        false,
        false,
        false, # vx, vy, vz
        false,
        false,
        false, # roll vel, pitch vel, YAW VELOCITY (not published)
        false,
        false,
        false,
      ] # acceleration
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true

    # 5. MA TRẬN NHIỄU (Tăng độ mượt - Tùy chọn nhưng nên có)
    # Nếu thấy robot trên RViz bị "rung", hãy tăng các giá trị trên đường chéo này lên
    process_noise_covariance:
      [
        0.05,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.05,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.06,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.03,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.03,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.06,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.025,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.025,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.04,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.01,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.01,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.02,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.01,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.01,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.015,
      ]
